jobs:
  - name: lint
    steps:
      - name: fmt
        run: gofumpt -w .
      - name: vet
        run: go vet ./...
      - name: lint
        run: golangci-lint run --output.tab.path=stdout

  - name: test
    steps:
      - name: unit
        run: go test -v ./...
      - name: race
        run: go test -v -race ./...

  - name: build
    steps:
      - name: build
        run: CGO_ENABLED=0 go build -ldflags="-s -w" -o bin/smallci

  - name: docker
    steps:
      - name: image
        run: docker buildx build -t smallci .

  - name: goreleaser
    steps:
      - name: snapshot
        run: GORELEASER_FORCE_TOKEN=github goreleaser release --skip sign --skip publish --snapshot --clean
