jobs:
  - name: lint-0
    steps:
      - name: fmt
        run: gofumpt -w .
      - name: vet
        run: go vet ./...
      - name: lint
        run: golangci-lint run --output.tab.path=stdout

  - name: test-0
    steps:
      - name: unit
        run: go test -v ./...
      - name: race
        run: go test -v -race ./...

  - name: lint-1
    steps:
      - name: fmt
        run: gofumpt -w .
      - name: vet
        run: go vet ./...
      - name: lint
        run: golangci-lint run --output.tab.path=stdout

  - name: test-1
    steps:
      - name: unit
        run: go test -v ./...
      - name: race
        run: go test -v -race ./...

  - name: lint-2
    steps:
      - name: fmt
        run: gofumpt -w .
      - name: vet
        run: go vet ./...
      - name: lint
        run: golangci-lint run --output.tab.path=stdout

  - name: test-2
    steps:
      - name: unit
        run: go test -v ./...
      - name: race
        run: go test -v -race ./...

  - name: build
    steps:
      - name: build
        run: go build -ldflags="-s -w" -o bin/smallci
        env:
          CGO_ENABLED: 0

  - name: docker
    steps:
      - name: image
        run: docker buildx build -t smallci .

  - name: goreleaser
    steps:
      - name: snapshot
        run: goreleaser release --skip sign --skip publish --snapshot --clean
        env:
          GORELEASER_FORCE_TOKEN: github
